# 第二章 R软件的使用 习题

## 2.2 矩阵运算

将1,2,...,20构成两个4x5价的矩阵，其中矩阵A按列输入，矩阵B按行输入：

```{r}
A <- matrix(1:20, nrow=4, ncol=5); A
B <- matrix(1:20, nrow=4, ncol=5, byrow=TRUE); B
```

### 1. 矩阵加法

```{r}
C <- A + B; C
```


### 2. 矩阵乘法

```{r}
D <- A %*% t(B); D
```


### 3. 矩阵各元素相乘

```{r}
E <- A * B; E
```


### 4. 矩阵前三行和前三列构成子矩阵

```{r}
F <- A[-4,-(4:5)]; F
```


### 5. 矩阵不包括第三列构成新矩阵

```{r}
G <- cbind(A[,1],A[,2],A[,4],A[,5]); G
```

## 2.3 向量构造

构造一个向量x，向量是由五个1，三个2，四个3，二个4构成，注意用到rep()函数

```{r}
# Better solution than c(rep(1,5),rep(2,3),rep(3,4),rep(4,2))
x=rep(1:4, c(5, 3, 4, 2)); x
```

## 2.4 Hilbert矩阵

### 1. 构造5阶hilbert矩阵

```{r}
n <- 5; h <- array(0, dim=c(n,n))
for (i in 1:n)
{
  for (j in 1:n)
  {
    h[i,j] <- 1/(i+j-1)
  }
}
h
# 另一种解法：先自定义Hilbert计算的操作符%!%,然后在向量外积计算中将计算函数重定义为fun=“%！%”
# hilbert = function(n){"%!%"=function(x,y){1/(x+y-1)};outer(1:n,1:n,"%!%")}
# h <- hilbert(5)
```

### 2. 求行列式

```{r}
det(h)
```

### 3. 求逆矩阵

```{r}
solve(h)
```

### 4. 求特征值和特征向量

```{r}
eigen(h)
```

