# 第三章 数据描述性分析 习题

## 3.1 女生血清蛋白分析

读入数据
```{r}
w <- as.vector(unlist(read.table("exec0301.data"))); w
```

计算均值(mean)、方差标准差(std_dev)、极差(R)、标准误(sm)、变异系数(cv)、偏度(Skewness)、峰度(Kurtosis)。
```{r}
source("../R-Book-Demo/ch3/data_outline.R", echo=TRUE, max.deparse.length=3e3)
data_outline(w)
```

## 3.5 小白鼠伤寒杆菌实验数据的箱线图

输入数据
```{r}
dm <- data.frame(
  J1=c(2, 4,3,2, 4,7, 7, 2, 2,5, 4,NA),
  J2=c(5, 6,8,5,10,7,12,12, 6,6,NA,NA),
  J3=c(7,11,6,6, 7,9, 5, 5,10,6, 3,10)
); t(dm)
```

使用boxplot画箱线图
```{r}
boxplot(dm$J1, dm$J2, dm$J3, names=c('J1', 'J2','J3'))
```

使用plot画箱线图
```{r}
plot(factor(c(rep(1,length(dm$J1)), rep(2,length(dm$J2)), rep(3,length(dm$J3)))), unlist(dm))
```

结论，J1菌型平均存活天数明显短于J2,J3菌型。

## 3.7 学生的四项指标散点图

读入数据
```{r}
# 从exam0203.txt直接读取数据，有表头
dt <- read.table("../R-Book-Demo/ch2/exam0203.txt", head=TRUE); dt
```

体重对于身高的散点图
```{r fig.height=5}
plot(dt$Weight,dt$Height,xlab="Weight",ylab="Height") 
```

不同性别情况下，体重对于身高的散点图
```{r fig.height=5}
coplot(dt$Weight ~ dt$Height | dt$Sex,
       xlab="Weight",ylab="Height")
```

不同年龄段下，体重对于身高的散点图
```{r}
coplot(dt$Weight ~ dt$Height | dt$Age,
       xlab="Weight",ylab="Height")
```

不同性别，不同年龄段下，体重对于身高的散点图
```{r fig.width=8}
coplot(dt$Weight ~ dt$Height | dt$Age + dt$Sex,
       xlab="Weight",ylab="Height")
```
