# 第三周作业

## 3.1 女生血清蛋白分析

读入数据
```{r}
w <- as.vector(unlist(read.table("exec0301.data"))); w
```

计算均值(mean)、方差标准差(std_dev)、极差(R)、标准误(sm)、变异系数(cv)、偏度(Skewness)、峰度(Kurtosis)。
```{r}
source("../R-Book-Demo/ch3/data_outline.R", echo=TRUE, max.deparse.length=3e3)
dow <- data_outline(w)
print(dow, digits=4)
```

## 3.2 女生血清蛋白分析图

直方图及密度估计曲线（绿色）以及正态密度曲线（红色）

```{r}
hist(w,20,col="blue",freq=F)
lines(density(w), lwd=2, col="green")
x <- min(w):max(w)
lines(x, dnorm(x,mean(w),sd(w)),col="red")
```

经验分布曲线与正态分布曲线（红色）
```{r}
plot(ecdf(w),verticals=T,do.p=F)
lines(x,pnorm(x,mean(w),sd(w),log.p=F), col="red")
```

正态QQ图和相应直线
```{r}
qqnorm(w)
qqline(w)
```


## 3.3 女生血清蛋白的茎叶图、箱线图及五数总括

```{r}
stem(w, scale=1)
boxplot(w,outline=F)
fivenum(w,na.rm=F)
```

## 3.4 正态分布检验

W检验方法
```{r}
shapiro.test(w)
```

Kolmogorov-Smirnov检验方法
```{r}
ks.test(w,"pnorm",mean(w),sd(w))
```

p值大于0.05，故数据可以认为是正态分布的。

## 3.9 用pearson检验法检验相关性

读入数据
```{r}
# 从exam0203.txt直接读取数据，有表头
dt <- read.table("../R-Book-Demo/ch2/exam0203.txt", head=TRUE); dt
```

检验
```{r}
cor.test(dt$Height,dt$Weight,methods = "Pearson")
```

因为p-value < 0.05，所以相关。

6.1

```{r}
x=c(5.1, 3.5, 7.1, 6.2, 8.8, 7.8, 4.5, 5.6, 8.0, 6.4)
y=c(1907,1287,2700,2373,3260,3000,1947,2273,3113,2493)
plot(x,y)
cor.test(x,y,methods="Pearson")
```
p-value = 6.33e-08 <0.05 所以相关

2)
```{r}
fm61<-data.frame(x,y)
lm.sol<-lm(y~x,data=fm61)
summary(lm.sol)
```
y=141+364.2x

3)
通过显著性检验

4)
```{r}
new<- data.frame(x=7)
predict(lm.sol,new,interval="prediction")
```
