# 第八次作业

## 对“WHO”数据集的MINE分析

### 设置MINE环境

#### [安装Java 7](http://www.webupd8.org/2012/01/install-oracle-java-jdk-7-in-ubuntu-via.html)

```bash
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java7-installer
sudo update-java-alternatives -s java-7-oracle
sudo apt-get install oracle-java7-set-default
```
#### [下载MINE](http://www.exploredata.net/Downloads/MINE-Application)

一共MINE.jar和MINE.R两个文件，可以放在当前工作目录，然后修改MINE.R第二行增大java的内存分配：

```text
library("rJava")
.jinit(classpath="MINE.jar",parameters="-Xms768m")
```

#### [下载WHO数据集](http://www.exploredata.net/Downloads/WHO-Data-Set)

```{r eval=FALSE}
download.file('http://www.exploredata.net/ftp/WHO.csv','WHO.csv')
```

### 进行MINE分析(时间较长)

```{r eval=FALSE}
setwd("~/R-SDSS/R-Book-Homework")
source('MINE.r')
MINE('WHO.csv','all.pairs')
```

### 读入结果

```{r}
who=read.csv('WHO.csv,allpairs,cv=0.0,B=n^0.6,Results.csv')
term=read.csv('WHO_term.csv')
```


### 取出显著相关的两两统计项

```{r}
strong=who[which(who$MIC..strength == 1),]
```

### 合并中英文对照表

```{r}
m=merge(strong,term, by.x = "X.var", by.y = "TermEn")
names(m)[names(m)=="TermCN"] <- "X.var.CN"
m=merge(m,term, by.x = "Y.var", by.y = "TermEn")
names(m)[names(m)=="TermCN"] <- "Y.var.CN"
m=m[,!(names(m) %in% c("SN.x","SN.y"))]
```

### 按照X.var排序

```{r}
res=m[with(m, order(X.var, Y.var)), ]
```

### 列出所有相关项目

```{r}
res[,c("X.var.CN","Y.var.CN")]
```

